# Generated by Django 4.2.23 on 2025-06-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('school_class', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.CharField(default='2023-2024', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['school_class', 'subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'Very good (like new)'), ('used', 'Normal use'), ('worn', 'Acceptable'), ('poor', 'Very used')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='book_offers/')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional condition details, markings, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('school_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='books.schoolbook')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolbook',
            index=models.Index(fields=['school_class', 'subject'], name='books_schoo_school__93a082_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbook',
            index=models.Index(fields=['section'], name='books_schoo_section_4a9a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbook',
            index=models.Index(fields=['isbn'], name='books_schoo_isbn_2c716e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentoffer',
            index=models.Index(fields=['school_book', 'is_active'], name='books_stude_school__f2e765_idx'),
        ),
        migrations.AddIndex(
            model_name='studentoffer',
            index=models.Index(fields=['seller', 'is_active'], name='books_stude_seller__339ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentoffer',
            index=models.Index(fields=['-created_at'], name='books_stude_created_462381_idx'),
        ),
    ]
